[package]
name = "sorting_algs"
version = "0.1.0"
authors = ["ibhatt <ibhatt@umich.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
